services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./apps/sinatra-api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "4567:4567"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/database
      RACK_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/sinatra-api:/app
    command: bundle exec rerun --dir . --pattern '**/*.rb' --force-polling -- rackup config.ru -p 4567 -o 0.0.0.0

volumes:
  postgres_data:
