# frozen_string_literal: true

source 'https://rubygems.org'

gem 'json',    '~> 2.7'
gem 'puma',    '~> 6.4'
gem 'rackup',  '~> 2.2'
gem 'sinatra', '~> 4.1'

group :development do
  gem 'rerun',   '~> 0.14'
  gem 'rubocop', require: false
end
