# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv',  '~> 3.1'
gem 'json',    '~> 2.7'
gem 'pg',      '~> 1.5'
gem 'puma',    '~> 6.4'
gem 'rackup',  '~> 2.2'
gem 'rake',    '~> 13.2'
gem 'sequel',  '~> 5.80'
gem 'sinatra', '~> 4.1'

group :development do
  gem 'rerun',   '~> 0.14'
  gem 'rubocop', require: false
end
